sudo: require
services:
  - docker

before_install:
  - docker build -t ajdeleon/docker-react -f Dockerfile.dev .

script:
  - docker run ajdeleon/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-run"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-us-east-2-741562941528"
  bucket_path: "docker-run"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
